#!/bin/sh
cd /websh
. ./html.sh

password=Je9leePha

# read HTTP message
read -r request
while true; do
	read -r header
	[ -z "$(echo "$header" | tr -d "[:space:]")" ] && break
	echo $header | grep -q "^Content-Length" && length=$(echo $header | grep -o "[0-9]*")
done

if [ -n "$length" ]; then
	post=$(dd bs=$length count=1 2>/dev/null)
fi

# HTTP request parsing
method=$(echo "$request" | cut -d\  -f1)
[ "$method" != "GET" -a "$method" != "POST" ] && exit
resource=$(echo "$request" | cut -d\  -f2)

request_parse() {
	query=$(echo "$2" | tr -cd '[:alnum:]-_.~!*'\''();:@&=+$,/?#[]%' | tr '&' "\n")
	while read -r getvar; do
		field="$(echo "$getvar" | cut -d\= -f1)"
		echo "$field" | grep -q '^[a-zA-Z_][a-zA-Z0-9_]*$' && eval $1_$field=\'"$(echo "$getvar" | cut -d\= -f2)"\'
	done <<EOT
$query
EOT
}

# resource parsing
path="$(echo "$resource" | cut -d\? -f1)"
if $(echo "$resource" | grep -q ?); then
	query="$(echo "$resource" | cut -d\? -f2)"
	request_parse 'get' "$query"
fi

# post parsing
request_parse 'post' "$post"

out="HTTP/1.1 200 OK\r\n"
out="${out}Cache-Control: no-store\r\n"
out="${out}Content-Type: text/html; charset=UTF-8\r\n"
out="${out}\r\n"

if [ "$get_pwd" != "$password" ]; then
	out="${out}You are not authorized!\r"
	echo -n "$out\r\n"
	exit
fi

# POST redirect
if [ "$method" = "POST" ]; then
	if [ -n "$post_msg" ]; then
		echo "[$(date '+%H:%M')]+$get_user::+$post_msg" | sed 's/+/%20/g' | sed 's % \\\\x g' | xargs printf >> data/carrychat.log
		echo >> data/carrychat.log
	fi
	echo "HTTP/1.1 303 See Other\r"
	echo "Location: $resource\r"
	echo "\r"
	exit
fi

msgs="$(tac data/carrychat.log \
| sed 's/</\&lt;/g; s/>/\&gt;/g; s/&/\&amp;/g' \
| sed 's/::/:<br \/>/g;' \
| sed -e "s|http[s]\?[:]//[^ ]*|<a target=\"_blank\" href=\"\0\">\0</a>|g" | sed 's/^/<p>/g; s/$/<\/p>/g' | tac)"

echo "$out$(eval "cat <<EOT
$(cat chat.html)
EOT")"

